spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080
  session:
    # 配置session存储策略
    store-type: jdbc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456